service:
  - name: "监控项模块"
    path: "item/index.yml"

  - name: "主机模块"
    path: "host/index.yml"

  - name: "登录模块"
    path: "login/index.yml"

  - name: "监控项延迟"
    path: "delay/index.yml"

  - name: "oracle数据库延迟"
    path: "oracle_delay_monitor/index.yml"

  - name: "trigger 获取"
    path: 'trigger/index.yml'

  - name: "alert 获取"
    path: 'alert/index.yml'

  - name: "install 安装模块"
    path: 'install/index.yml'


  - name: "group 分组模块"
    path: 'group/index.yml'

  - name: "template 模板模块"
    path: 'template/index.yml'

  - name: "task 模板模块"
    path: 'task/index.yml'

  - name: "interface 模板模块"
    path: 'interface/index.yml'

  - name: "proxy 代理"
    path: 'proxy/index.yml'